### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by steinbrueckri** [theoapp/theo-node#35]

**Comment by macno** [comment]
Hi @steinbrueckri ! Thanks for your interest in theo!
I've been able to add the support for PostgreSQL in a testing branch, would you like to test a beta version? I can build and push an image

**Comment by steinbrueckri** [comment]
@macno Thx for the feedback, yes of cause. I'm very interested in the project and happy to help you.

**Comment by macno** [comment]
@steinbrueckri here we are:

`docker pull macno77/theo:1.4.0-beta.0-postgres-redis`

all you need is to set `DB_ENGINE=postgres`

these is a simple example using docker-compose to start testing:

```yaml
version: '3.1'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  cache:
    image: redis:6
  theo:
    image: macno77/theo:1.4.0-beta.0-postgres-redis
    environment:
      DB_ENGINE: postgres
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      CLIENT_TOKENS: ${CLIENT_TOKENS}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      DB_CONN_MAX_RETRY: 30
    ports:
      - 9100:9100
    depends_on:
      - cache
      - db
```
